-- Monitor wiki https://wiki.hypr.land/Configuring/Basics/Monitors/
-- Example: output can be found with hyprctl monitors. Edit variables.lua for the monitor outputs instead of here directly
-- hl.monitor({
--     output    = MONITOR1,
--     mode      = "1920x1080@60",
--     position  = "0x0",
--     scale     = "1",
-- })

-- hl.monitor({
--     output    = MONITOR1,
--     mode      = "preferred",
--     position  = "auto",
--     scale     = "auto",
-- })
--
-- Laptop panel off while the external monitor is used.
-- To get it back, comment this out (or run: hyprctl keyword monitor eDP-1,preferred,auto,1)
-- hl.monitor({
--     output   = MONITOR2,
--     disabled = true,
-- })
